// frontend-vue/src/App.vue
<script setup lang="ts">

import { computed } from 'vue'
import { RouterLink, RouterView, useRoute } from "vue-router";
import { storeToRefs } from 'pinia'
import { useAuthStore } from './stores/auth';
import { useShopStore } from './stores/shop';

const apiURL = import.meta.env.VITE_API_URL

const authStore = useAuthStore()
const { isAuth, email } = storeToRefs(authStore)
const { logout } = authStore

const shopStore = useShopStore()
const { cart } = storeToRefs(shopStore)

const route = useRoute();
const currentPath = computed(() => route.path);

function onLogout() {
  logout()
}

</script>

<template>
    <div class="container mx-auto p-8">
      <header class="container mx-auto py-8">
      <nav class="text-sm uppercase flex flex-row justify-between">
          <ul class="flex flex-row">

            <li :class="['/', '/shop'].includes(currentPath) ? 'font-bold' : ''">
              <router-link to="/shop">shop</router-link>
            </li>
            
            <li class="px-1">|</li>            
            <li :class="['/cart'].includes(currentPath) ? 'font-bold' : ''">
              <router-link to="/cart">{{`Cart ${cart.length ? '(' + cart.length + ')' : ''} `}}</router-link>
            </li>
          </ul>
          <ul class="flex flex-row">
            <li class='justify-self-end' v-if="!isAuth">
              <router-link to="/login">login</router-link>
            </li>
            <li class='justify-self-end' v-if="isAuth">
              <span v-on:click="() => {onLogout()}" >logout {{ email }}</span>
            </li>

          </ul>
      </nav>    
      <hr />
    </header> 
    <router-view></router-view>
    <footer class='pt-8'>
      <hr class="p-2" />
      <p class='text-sm'>apiUrl: {{ apiURL }}</p>
    </footer>     
    </div>

  
</template>

<style>
</style>

// frontend/src/App.tsx
import React, { useContext, useEffect, useState } from 'react';
import { Outlet, Link, useLocation } from "react-router-dom";
import { ShopContext } from './providers/shop'

function App() {

  const [initialLoad, setInitialLoad] = useState(false)
  const { pathname }  = useLocation()
  const apiURL = process.env.REACT_APP_API_URL ?? 'NO_API'

  const { state: { cart, auth }, fetchShoes, logout} = useContext(ShopContext);

  useEffect(() => {
    if (fetchShoes && ! initialLoad) {
      fetchShoes(true)
      setInitialLoad(true)
    }
  }, [fetchShoes, initialLoad],)


  return (
    <div className="container mx-auto p-8">
      <header className="container mx-auto py-8">
      <nav className="text-sm uppercase flex flex-row justify-between">
          <ul className="flex flex-row">
            <li className={['/', '/shop'].includes(pathname) ? 'font-bold': ''} ><Link to="/shop">Shop</Link></li>
            <li className="px-1">|</li>
            <li className={['/cart'].includes(pathname) ? 'font-bold': ''} ><Link to="/cart">{`Cart ${cart.length ? '(' + cart.length + ')' : ''} `}</Link></li>
          </ul>
          <ul className="flex flex-row">
            { !auth.isLogged && <li className='justify-self-end' >
              <Link to="/login">Login</Link>
            </li> }
            { auth.isLogged && <li className='justify-self-end' >
                <span onClick={() => logout!()} >Logout ({auth.email}) </span></li> }
          </ul>
      </nav>    
      <hr />
    </header> 
    <Outlet />
    <footer className='pt-8'>
      <hr className="p-2" />
      <p className='text-sm'>apiUrl: {apiURL}</p>
    </footer>     
    </div>
  );
}

export default App;
